source 'https://rubygems.org'
gem 'ddtrace'
gem 'sinatra' 
gem 'activerecord', '4.2.5' 
gem 'sinatra-activerecord' 
gem 'rake'
gem 'thin' 
gem 'require_all' 
gem 'pg' 
gem 'faker'
gem 'dogstatsd-ruby'
gem 'byebug'
group :development do
  gem 'shotgun'
  gem 'pry'
  gem 'tux'
end
